FROM python:3.10-slim

# Set a working directory inside the container
WORKDIR /app

# Copy your entire src/ folder into the container
COPY src/ ./src/

# Run the main script
CMD ["python", "src/hello.py"]
